import { walk } from "https://deno.land/std@0.224.0/fs/walk.ts";
import { ensureDir } from "https://deno.land/std@0.224.0/fs/ensure_dir.ts";
import { join, relative, basename } from "https://deno.land/std@0.224.0/path/mod.ts";

const distPath = "./dist";
const cssDir = "./dist/css";
const outputFile = join(distPath, "styles.css");

export async function transformSCSS_WP() {
  const start = performance.now();

  try {
    await ensureDir(distPath);

    const cssFiles: string[] = [];

    for await (const entry of walk(cssDir, { includeFiles: true, exts: ["css"] })) {
      if (entry.path.endsWith("styles.css")) continue; // skip itself
      cssFiles.push(entry.path);
    }

    cssFiles.sort();

    let combined = `/* 
------------------------------------------------------
            styles.css for wordpress
           all css files from dist/css
         generated by transformSCSS_WP.ts
------------------------------------------------------
*/\n\n`;

    for (const file of cssFiles) {
      try {
        const cssContent = await Deno.readTextFile(file);
        const srcFileName = basename(file);
        combined += `/* __________ ${srcFileName} __________ */\n`;
        combined += cssContent + "\n\n";
      } catch (_e) {
      }
    }


    await Deno.writeTextFile(outputFile, combined);

    const end = performance.now();
    console.log(`\x1B[38;5;200mwp-styles\x1B[0m combined in ${Math.round(end - start)}ms`);
  } catch (error) {
    console.error("❌ transformSCSS_WP error:", error);
  }
}
